jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Run unit tests and assemble APKs
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleProdRelease testProdReleaseUnitTest
    - continue-on-error: true
      name: Check Output
      run: bash ./etc/CheckBuild/check-release.sh test
    strategy:
      matrix:
        java-version:
        - 11
name: Unit Test
on:
  repository_dispatch:
    types: trigger-ga___unit_test.yml
